- name: add redis stable repository from PPA and install its signing key.
  apt_repository: repo="ppa:chris-lea/redis-server"
- name: install redis.
  apt:  pkg=redis-server update_cache=yes force=yes
- name: be sure redis is running and enabled.
  service: name=redis-server state=running enabled=yes
